name: build

on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  #pull_request:
  #push:
  #  branches:
  #    - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/workflow_devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/workflow_devcontainer
          push: never
          runCmd: npm run build && npm run test -- --json --outputFile=\"report.json\"

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          skip-step: all
          coverage-file: report.json
          base-coverage-file: report.json
          output: comment, report-markdown
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo '${{ steps.coverage.outputs.report }}' >> $GITHUB_STEP_SUMMARY

# build-push-action
#   https://github.com/docker/build-push-action
# Test before push
#   https://docs.docker.com/build/ci/github-actions/test-before-push/
