name: build

on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  #pull_request:
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/exabugs/node-dev-container
          cacheFrom: ghcr.io/exabugs/node-dev-container
          push: always
          runCmd: npm run build && npm run test -- --json --outputFile=\"report.json\"

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          skip-step: all
          coverage-file: report.json
          base-coverage-file: report.json
          output: comment, report-markdown
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo '${{ steps.coverage.outputs.report }}' >> $GITHUB_STEP_SUMMARY
