name: build

on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  #pull_request:
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      #- name: Build and run dev container task
      #  uses: devcontainers/ci@v0.3
      #  with:
      #    runCmd: yarn build && yarn test

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          #skip-step: all
          #coverage-file: ./coverage/coverage-final.json
          #base-coverage-file: ./coverage/coverage-final.json
          output: report-markdown
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo '${{ steps.coverage.outputs.report }}' >> $GITHUB_STEP_SUMMARY
