name: build

on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  #pull_request:
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      #- name: Build and run dev container task
      #  uses: devcontainers/ci@v0.3
      #  with:
      #    runCmd: npm run build && npm run test

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          #working-directory: coverage
          skip-step: all
          #coverage-file: coverage-final.json
          #base-coverage-file: coverage-final.json
          output: comment, report-markdown
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo '${{ steps.coverage.outputs.report }}' >> $GITHUB_STEP_SUMMARY
