name: build

on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  #pull_request:
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to be your CI task/script
          runCmd: yarn build && yarn test

      - run: |
          echo '# Coverage :rocket:' >> $GITHUB_STEP_SUMMARY
          # sed で先頭行と末尾行の不要な罫線を消す
          cat coverage/report.txt | sed -e '1d' -e '$d' >> $GITHUB_STEP_SUMMARY
