name: release
on:
  workflow_dispatch:

  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  TZ: Asia/Tokyo
  IMAGE_NAME: node-dev-container

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/workflow_devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/workflow_devcontainer
          push: never
          runCmd: npm run build

      #- name: image build and push
      #  run: |
      #    IMAGE_VER=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
      #    [[ -n $IMAGE_VER ]] || IMAGE_VER=v$(date +"%Y%m%d%H%M")

      #    echo "build ${IMAGE_NAME}:${IMAGE_VER}"

      #    TAG=ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_VER}

      #    docker build . -t $TAG
      #    docker push $TAG

      - name: Check Tag
        run: |
          IMAGE_VER=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          [[ -n $IMAGE_VER ]] || IMAGE_VER=v$(date +"%Y%m%d%H%M")

          echo "build ${IMAGE_NAME}:${IMAGE_VER}"

          TAG=ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_VER}

          echo "TAG=$TAG" >> $GITHUB_ENV

      # イメージをビルドして、ECR にプッシュする
      # https://cockscomb.hatenablog.com/entry/2022/02/16/092538
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
