name: release 
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  TZ: 'Asia/Tokyo'
  IMAGE_NAME: node-dev-container

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: yarn build

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: image build and push
        run: |
          IMAGE_VER=v$(date +"%Y%m%d%H%M")
          echo "build ${IMAGE_NAME}:${IMAGE_VER}"

          TAG=ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_VER}

          docker build . -t $TAG
          docker push $TAG

      #- name: Build and push Docker image
      #  uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}
